### ISSUE TITLE
Should we be using the issues section

### ISSUE THREAD

**Issue by Ryex** [borisblizzard/arcreator#1]
Personally I find it quite useful to make use of the issues section here on github.
I very much like to get everyone using it if at all possible. thoughts?

**Comment by tcrane20** [comment]
I don't see why not. Helps keep track of "hidden" TODOs lying around.

**Comment by Ryex** [comment]
I that case I'll proceed to use it feel free to follow suit

**Comment by borisblizzard** [comment]
I agree very much. It's better to have it in one place as opposed to the
forum.
What about tasks? Should we move it, too? Does github have something like
that? Or can Issues be used for that?

**Comment by Ryex** [comment]
Issues can be used as tasks. There is a feature tag after all.
