### ISSUE TITLE
Mention the move to GitHub on the Google Code page

### ISSUE THREAD

**Issue by akien-mga** [borisblizzard/arcreator#31]
Hi there,

I was browsing Google Code for dead projects that might need archiving on GitHub (I'm running @LibreGameArchive) when I found arcreator. It doesn't seem dead at all, but it would be nice if you could mention the move to GitHub on the Google Code main page, so that it's clear to anyone landing on this page.

I only noticed that you had a GitHub repo after I had cloned the whole SVN repo and seen the "ARC HAS MOVED.txt" file :)

**Comment by Ryex** [comment]
Done, thanks for pointing out it hadn't be mentioned in the front page
